#!/usr/bin/env python
import sys


usage = """\
download_koa filename outputfilename

Download a fits file from the Keck Observatory archive.

e.g.  download_koa HI.20060703.20567.fits trace.fits
"""
args = sys.argv[1:]

if len(args) != 2:
    print usage
    sys.exit()

import urllib2

filename, outname = args

date = filename.split('.')[1]
print 'Opening KOA page:'
s = 'https://koa.ipac.caltech.edu/cgi-bin/getHIRES/nph-getHIRES?filehand=/koadata4/HIRES/%s/lev0/%s' % (date, filename)
print s
response = urllib2.urlopen(s)
print 'Reading response'
d = response.read()

# try:
#     i = d.index('<!--END RESULTS_SCI COLUMNS-->')
# except ValueError:
#     print filename, ' not found'
#     sys.exit()

# i1 = i + d[i:].index('<a href="') + len('<a href="')
# i2 = i1 + d[i1:].index('"')
# address = d[i1:i2]
# print 'opening link'
# response = urllib2.urlopen('https://koa.ipac.caltech.edu' + address)
# print '%s found, downloading...' % filename
# data = response.read()

print 'Writing to %s' % outname
fh = open(outname, 'wb')
fh.write(d)
fh.close()
