#!/usr/bin/env python
from barak.fitcont import fitqsocont
from barak.io import writetable
from atpy import Table
import sys
import numpy as np

np.seterr(invalid='ignore', divide='ignore')

if 1:
    if len(sys.argv[1:]) != 3:
        print './fitcontinuum.py redshift inputfile outputfile'
        sys.exit()

    redshift = float(sys.argv[1])
    inname, outname = sys.argv[2:]
    sp = Table(inname)
    print 'press "q" when done, and then close the plotting window'
    junk = fitqsocont(sp.wa, sp.fl, sp.er, redshift, divmult=4, atmos=True)
    if junk[0] is None:
        sys.exit()
    sp.add_column('co', junk[0])
    writetable(outname, sp, overwrite=1)

