#!/usr/bin/env python
from __future__ import print_function, absolute_import, division, unicode_literals


import sys

if len(sys.argv[1:]) != 3:
    print('./fitcontinuum.py redshift inputfile outputfile')
    sys.exit()

from linetools.analysis.continuum import find_continuum
from linetools.spectra.xspectrum1d import XSpectrum1D

from astropy.table import Table, Column
import numpy as np

np.seterr(invalid='ignore', divide='ignore')

if 1:
    redshift = float(sys.argv[1])
    inname, outname = sys.argv[2:]
    T = Table.read(inname)
    print('press "q" when done, and then close the plotting window')
    spec = XSpectrum1D.from_tuple((T['wa'], T['fl'], T['er']))
    spec.fit_continuum(redshift=redshift, kind='QSO',
                       divmult=4, forest_divmult=4)
    spec.write_to_fits(outname)

