#!/usr/bin/env python
""" Rebin individual HIRES exposures to a common wavelength scale, and
make a rough combination of all the spectra to act as a template for
use scaling the spectra.
"""

import numpy as np
try:
    from astropy.io import fits 
except ImportError:
    import pyfits as fits
from pylab import plot,show

import sys, os

from barak.utilities import between
from HIRES.core import read_HIRES_wascale, rebin

# read all the (extracted) spectra

# read a fiel wavelength shifts, if 

if 1:
    fluxnames = sorted(sys.argv[1:])
    assert fluxnames
    if 'Flux-' in fluxnames[0]:
        errnames = [n.replace('Flux-', 'Err-') for n in fluxnames]
        skynames = [n.replace('Flux-', 'Sky-') for n in fluxnames]
    elif '_Flux.fits' in fluxnames[0]:
        errnames = [n.replace('_Flux.fits','_Err.fits') for n in fluxnames]
        skynames = [n.replace('_Flux.fits','_Sky.fits') for n in fluxnames]
    else:
        raise ValueError('Unknown naming scheme!')

    Nexp = len(fluxnames)

    wavs = []
    flux = []
    error = []
    bgs = []
    IDs = []
    for i in range(Nexp):
        fluxname = fluxnames[i]
        errname = errnames[i]
        skyname = skynames[i]
        print 'reading', fluxname, '+ Err + Sky' 
        #import pdb; pdb.set_trace()
        wa = read_HIRES_wascale(fluxname)
        wavs.extend(wa)
        flux.extend(fits.getdata(fluxname))
        error.extend(fits.getdata(errname))
        bgs.extend(fits.getdata(skyname))
        prefix = os.path.split(fluxname)[-1].split('.')[0]
        IDs.extend(['%s-%i' % (prefix, i+1) for i in xrange(len(wa))])

    # for i in range(len(wavs)):
    #         plot(wavs[i], flux[i])
    #         plot(wavs[i], error[i])
    # show()

if 1:
    # rebin orders
    # sort in order of increasing first bin wavelength
    isort = np.argsort([wa[0] for wa in wavs])
    wavs = [wavs[i] for i in isort]
    flux = [flux[i] for i in isort]
    error = [error[i] for i in isort]
    bgs = [bgs[i] for i in isort]
    IDs = [IDs[i] for i in isort]
    wmin = min([wa[0] for wa in wavs])
    wmax = max([wa[-1] for w in wavs])

    # Create a wavelength scale with constant
    # that covers all the individual exposures
    delta = 2.2 / 3.e5
    print 'using %.2f km/s pixels' % (delta * 3e5)
    dlog10wa = np.log10(1 + delta)
    log10wa = np.arange(np.log10(wmin), np.log10(wmax), dlog10wa)
    wa = 10**log10wa

    print 'rebinning'
    if not os.path.lexists('./rebinned'):
        os.mkdir('./rebinned')
    fh = open('Rebinned_IDs', 'wt')
    wa = np.array(wa, np.float32)
    for i in range(len(wavs)):
        #print '%i %s' % (i,IDs[i])
        if not i % 20: print i, 'of', len(wavs)
        fl, er = rebin(wavs[i], flux[i], error[i], wa)
        bg = np.interp(wa, wavs[i], bgs[i])
        er = np.array(er, np.float32)
        fl = np.array(fl, np.float32)
        bg = np.array(bg, np.float32)        
        sp = np.rec.fromarrays([wa, fl, er, bg], names='wa,fl,er,bg')
        np.save('rebinned/%03i.npy' % i, sp)
        fh.write('%i %s\n' % (i,IDs[i]))

    fh.close()
